apiVersion: apps/v1
kind: Deployment
metadata:
  name: auction-runner
  labels:
    app: auction-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auction-runner
  template:
    metadata:
      labels:
        app: auction-runner
        proxy.atomix.io/inject: "true"
        proxy.atomix.io/profile: "ixp-storage-profile"
    spec:
      containers:
      - name: auction-runner
        image: auction-runner:local
        env:
          - name: KAFKA_BOOTSTRAP
            value: "ixp-kafka-kafka-bootstrap:9092"
          - name: SCENARIO_PATH
            value: /etc/scenario/scenario.yaml
        volumeMounts:
          - name: scenario-volume
            mountPath: /etc/scenario
            readOnly: true

      volumes:
        - name: scenario-volume
          configMap:
            name: test-scenario