apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telemetry-service
  template:
    metadata:
      labels:
        app: telemetry-service
        proxy.atomix.io/inject: "true"
        proxy.atomix.io/profile: "ixp-storage-profile"
    spec:
      containers:
      - name: telemetry-service
        image: telemetry-service:local
        env:
        - name: KAFKA_BOOTSTRAP
          value: "ixp-kafka-kafka-bootstrap:9092"
